export const GET_ALL_OWNERSHIPS = "GET_ALL_OWNERSHIPS";
export const HANDLE_OWNER_TX_HISTORY_INPUT = "HANDLE_OWNER_TX_HISTORY_INPUT";
export const OWNER_TX_HISTORY = "OWNER_TX_HISTORY";

export const GET_ALL_ASSETS = "GET_ALL_ASSETS";
export const HANDLE_ASSET_TX_HISTORY_INPUT = "HANDLE_ASSET_TX_HISTORY_INPUT";
export const ASSET_TX_HISTORY = "ASSET_TX_HISTORY";

export const TRANSFER = "TRANSFER";
export const HANDLE_TRANSFER_FROM_INPUT = "HANDLE_TRANSFER_FROM_INPUT";
export const HANDLE_TRANSFER_RECEIVER = "HANDLE_TRANSFER_RECEIVER";
export const HANDLE_TOKEN_AMOUNT_INPUT = "HANDLE_TOKEN_AMOUNT_INPUT";
export const HANDLE_TRANSFER_SUBMIT = "HANDLE_TRANSFER_SUBMIT";

export const CHECK_OWNERSHIP = "CHECK_OWNERSHIP";
export const GET_ASSET_OWNERS = "GET_ASSET_OWNERS";
export const HANDLE_ASSET_DIST_INPUT = "HANDLE_ASSET_DIST_INPUT";
export const ASSET_DIST = "ASSET_DIST";

export const CREATE_OWNER = "CREATE_OWNER";
export const CREATEOWNERSHIP_INPUT_ONCHANGE = "CREATEOWNERSHIP_INPUT_ONCHANGE";
export const HANDLE_OWNERSHIP_ASSETID_ONCHANGE =
  "HANDLE_OWNERSHIP_ASSETID_ONCHANGE";

export const HANDLE_OWNERSHIP_CONFIRMATION_MODAL_VISIBLE =
  "HANDLE_OWNERSHIP_CONFIRMATION_MODAL_VISIBLE";
export const HANDLE_OWNERSHIP_CONFIRMATION_SUBMODAL_VISIBLE =
  "HANDLE_OWNERSHIP_CONFIRMATION_SUBMODAL_VISIBLE";
export const HANDLE_OWNERSHIPID_ONCHANGE = "HANDLE_OWNERSHIPID_ONCHANGE";
export const HANDLE_OWNERSHIP_NEWASSETID = "HANDLE_OWNERSHIP_NEWASSETID";
export const HANDLE_OWNERSHIP_TOKEN_NUMBER_INPUT_ONCHANGE =
  "HANDLE_OWNERSHIP_TOKEN_NUMBER_INPUT_ONCHANGE";
export const OWNERSHIP_ON_NEW_OWNER_ADDED = "OWNERSHIP_ON_NEW_OWNER_ADDED";
export const OWNERSHIP_HANDLE_NEW_ASSETID_ON_ADDED =
  "OWNERSHIP_HANDLE_NEW_ASSETID_ON_ADDED";
export const OWNERSHIP_FILL_ASSET_SELECTION = "OWNERSHIP_FILL_ASSET_SELECTION";
